<?php

namespace AppBundle\Repository;

/**
 * LinhaPesquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinhaPesquisaRepository extends \Doctrine\ORM\EntityRepository
{
}
