<?php

namespace AppBundle\Repository;

/**
 * OrientadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrientadorRepository extends \Doctrine\ORM\EntityRepository
{
}
