<?php

namespace AppBundle\Repository;

/**
 * TrabalhoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabalhoRepository extends \Doctrine\ORM\EntityRepository
{
}
